name: Build project
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build project
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: clean build
      - name: Deploy project
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: L11cov@yandex.ru